defmodule Nspark.Repo.Migrations.AddRunEventIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:run_events, [:organization_id, :graph_id, :inserted_at])

    create index(:run_events, [:organization_id, :inserted_at])
  end

  def down do
    drop_if_exists index(:run_events, [:organization_id, :inserted_at])

    drop_if_exists index(:run_events, [:organization_id, :graph_id, :inserted_at])
  end
end
