defmodule Nspark.Repo.Migrations.AddRegistryDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:skills, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :content, :text
      add :version, :bigint, null: false, default: 1
      add :status, :text, null: false, default: "draft"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "skills_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create table(:schemas, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :content, :text
      add :format, :text, null: false, default: "json"
      add :version, :bigint, null: false, default: 1
      add :status, :text, null: false, default: "draft"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "schemas_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create table(:policies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :content, :text
      add :category, :text, null: false, default: "safety"
      add :version, :bigint, null: false, default: 1
      add :status, :text, null: false, default: "draft"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "policies_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create table(:packages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :persona_content, :text
      add :version, :bigint, null: false, default: 1
      add :status, :text, null: false, default: "draft"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "packages_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create table(:package_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :asset_type, :text, null: false
      add :asset_id, :uuid, null: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "package_items_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :package_id,
          references(:packages,
            column: :id,
            name: "package_items_package_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:package_items, [:organization_id, :package_id, :asset_type, :asset_id],
             name: "package_items_unique_package_asset_index"
           )

    create table(:memory_templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :content, :text
      add :kind, :text, null: false, default: "episodic"
      add :version, :bigint, null: false, default: 1
      add :status, :text, null: false, default: "draft"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "memory_templates_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:memory_templates, "memory_templates_organization_id_fkey")

    drop table(:memory_templates)

    drop constraint(:package_items, "package_items_organization_id_fkey")

    drop constraint(:package_items, "package_items_package_id_fkey")

    drop_if_exists unique_index(
                     :package_items,
                     [:organization_id, :package_id, :asset_type, :asset_id],
                     name: "package_items_unique_package_asset_index"
                   )

    drop table(:package_items)

    drop constraint(:packages, "packages_organization_id_fkey")

    drop table(:packages)

    drop constraint(:policies, "policies_organization_id_fkey")

    drop table(:policies)

    drop constraint(:schemas, "schemas_organization_id_fkey")

    drop table(:schemas)

    drop constraint(:skills, "skills_organization_id_fkey")

    drop table(:skills)
  end
end
