defmodule Nspark.Repo.Migrations.AddTestScenarios do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:test_scenarios, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false, default: "New scenario"
      add :given_state, :text
      add :given_memory, :map, null: false, default: %{}
      add :given_conds, {:array, :text}, null: false, default: []
      add :expect, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "test_scenarios_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :graph_id,
          references(:graphs,
            column: :id,
            name: "test_scenarios_graph_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:test_scenarios, "test_scenarios_organization_id_fkey")

    drop constraint(:test_scenarios, "test_scenarios_graph_id_fkey")

    drop table(:test_scenarios)
  end
end
