defmodule Nspark.Repo.Migrations.AddGraphVersionInputContract do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:graph_versions) do
      add :input_contract, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:graph_versions) do
      remove :input_contract
    end
  end
end
