defmodule Nspark.Repo.Migrations.AddDeployments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:deployments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :environment, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :endpoint_slug, :text, null: false
      add :deployed_version, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "deployments_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :project_id,
          references(:projects,
            column: :id,
            name: "deployments_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :graph_version_id,
          references(:graph_versions,
            column: :id,
            name: "deployments_graph_version_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:deployments, "deployments_organization_id_fkey")

    drop constraint(:deployments, "deployments_project_id_fkey")

    drop constraint(:deployments, "deployments_graph_version_id_fkey")

    drop table(:deployments)
  end
end
