defmodule Nspark.Repo.Migrations.AddCoreDomains do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "draft"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id, :uuid, null: false
    end

    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:projects) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "projects_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:organizations) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :settings, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    create table(:nodes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :label, :text, null: false
      add :content, :text
      add :metadata, :map, default: %{}
      add :is_muted, :boolean, null: false, default: false
      add :source_asset_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "nodes_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :graph_id, :uuid, null: false
    end

    create table(:graphs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:nodes) do
      modify :graph_id,
             references(:graphs,
               column: :id,
               name: "nodes_graph_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:graphs) do
      add :name, :text, null: false
      add :description, :text
      add :graph_version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "graphs_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :project_id,
          references(:projects,
            column: :id,
            name: "graphs_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create table(:graph_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_number, :bigint, null: false
      add :changelog, :text
      add :graph_snapshot, :map, null: false, default: %{}
      add :author_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "graph_versions_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :graph_id,
          references(:graphs,
            column: :id,
            name: "graph_versions_graph_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create table(:edges, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :edge_type, :text, null: false, default: "dependency"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "edges_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :graph_id,
          references(:graphs,
            column: :id,
            name: "edges_graph_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :source_node_id,
          references(:nodes,
            column: :id,
            name: "edges_source_node_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :target_node_id,
          references(:nodes,
            column: :id,
            name: "edges_target_node_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:edges, "edges_organization_id_fkey")

    drop constraint(:edges, "edges_graph_id_fkey")

    drop constraint(:edges, "edges_source_node_id_fkey")

    drop constraint(:edges, "edges_target_node_id_fkey")

    drop table(:edges)

    drop constraint(:graph_versions, "graph_versions_organization_id_fkey")

    drop constraint(:graph_versions, "graph_versions_graph_id_fkey")

    drop table(:graph_versions)

    drop constraint(:graphs, "graphs_organization_id_fkey")

    drop constraint(:graphs, "graphs_project_id_fkey")

    alter table(:graphs) do
      remove :project_id
      remove :organization_id
      remove :updated_at
      remove :inserted_at
      remove :graph_version
      remove :description
      remove :name
    end

    drop constraint(:nodes, "nodes_graph_id_fkey")

    alter table(:nodes) do
      modify :graph_id, :uuid
    end

    drop table(:graphs)

    drop constraint(:nodes, "nodes_organization_id_fkey")

    drop table(:nodes)

    drop_if_exists unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    alter table(:organizations) do
      remove :updated_at
      remove :inserted_at
      remove :settings
      remove :slug
      remove :name
    end

    drop constraint(:projects, "projects_organization_id_fkey")

    alter table(:projects) do
      modify :organization_id, :uuid
    end

    drop table(:organizations)

    drop table(:projects)
  end
end
