defmodule Nspark.Repo.Migrations.AddApiKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :prefix, :text, null: false
      add :hash, :text, null: false
      add :environment, :text
      add :last_used_at, :utc_datetime_usec
      add :expires_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "api_keys_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :project_id,
          references(:projects,
            column: :id,
            name: "api_keys_project_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :created_by_id,
          references(:users,
            column: :id,
            name: "api_keys_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :revoked_by_id,
          references(:users,
            column: :id,
            name: "api_keys_revoked_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:api_keys, [:hash], name: "api_keys_unique_hash_index")
  end

  def down do
    drop constraint(:api_keys, "api_keys_organization_id_fkey")

    drop constraint(:api_keys, "api_keys_project_id_fkey")

    drop constraint(:api_keys, "api_keys_created_by_id_fkey")

    drop constraint(:api_keys, "api_keys_revoked_by_id_fkey")

    drop_if_exists unique_index(:api_keys, [:hash], name: "api_keys_unique_hash_index")

    drop table(:api_keys)
  end
end
