defmodule Nspark.Repo.Migrations.AddEdgeMetadata do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:edges) do
      add :metadata, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:edges) do
      remove :metadata
    end
  end
end
