defmodule Nspark.Repo.Migrations.AddRunEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:run_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source, :text, null: false
      add :status, :text, null: false, default: "ok"
      add :http_status, :bigint
      add :resolved_via, :text
      add :latency_ms, :bigint
      add :token_estimate, :bigint
      add :error_reason, :text
      add :principal_type, :text
      add :variable_keys, {:array, :text}, null: false, default: []
      add :outcome, :text, null: false, default: "unrated"
      add :feedback_note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "run_events_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :graph_id,
          references(:graphs,
            column: :id,
            name: "run_events_graph_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :graph_version_id,
          references(:graph_versions,
            column: :id,
            name: "run_events_graph_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :deployment_id,
          references(:deployments,
            column: :id,
            name: "run_events_deployment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :api_key_id,
          references(:api_keys,
            column: :id,
            name: "run_events_api_key_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:run_events, "run_events_organization_id_fkey")

    drop constraint(:run_events, "run_events_graph_id_fkey")

    drop constraint(:run_events, "run_events_graph_version_id_fkey")

    drop constraint(:run_events, "run_events_deployment_id_fkey")

    drop constraint(:run_events, "run_events_api_key_id_fkey")

    drop table(:run_events)
  end
end
