defmodule Nspark.Repo.Migrations.AddMembershipAndInvitations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "viewer"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "memberships_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:memberships, [:user_id, :organization_id],
             name: "memberships_unique_user_org_index"
           )

    create table(:invitations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :role, :text, null: false, default: "viewer"
      add :token, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :expires_at, :utc_datetime_usec
      add :accepted_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "invitations_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :invited_by_id,
          references(:users,
            column: :id,
            name: "invitations_invited_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:invitations, [:token], name: "invitations_unique_token_index")
  end

  def down do
    drop constraint(:invitations, "invitations_organization_id_fkey")

    drop constraint(:invitations, "invitations_invited_by_id_fkey")

    drop_if_exists unique_index(:invitations, [:token], name: "invitations_unique_token_index")

    drop table(:invitations)

    drop constraint(:memberships, "memberships_user_id_fkey")

    drop constraint(:memberships, "memberships_organization_id_fkey")

    drop_if_exists unique_index(:memberships, [:user_id, :organization_id],
                     name: "memberships_unique_user_org_index"
                   )

    drop table(:memberships)
  end
end
