defmodule Nspark.Repo.Migrations.AddGraphVersionDiffSummary do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:graph_versions) do
      add :diff_summary, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:graph_versions) do
      remove :diff_summary
    end
  end
end
