defmodule Nspark.Repo.Migrations.AddGraphSlug do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Add nullable first so existing rows survive, then backfill a slug derived
    # from each graph's name (matching Nspark.Slug.slugify/1), suffixed with a
    # slice of the id to guarantee per-org uniqueness, before enforcing NOT NULL.
    alter table(:graphs) do
      add :slug, :text, null: true
    end

    flush()

    execute("""
    UPDATE graphs
    SET slug =
      coalesce(
        nullif(trim(both '-' from regexp_replace(lower(coalesce(name, '')), '[^a-z0-9]+', '-', 'g')), ''),
        'prompt'
      ) || '-' || substr(id::text, 1, 8)
    WHERE slug IS NULL
    """)

    execute("ALTER TABLE graphs ALTER COLUMN slug SET NOT NULL")

    create unique_index(:graphs, [:organization_id, :slug], name: "graphs_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:graphs, [:organization_id, :slug],
                     name: "graphs_unique_slug_index"
                   )

    alter table(:graphs) do
      remove :slug
    end
  end
end
